apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tools
  labels:
    app: network-tools
    environment: stag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-tools
  template:
    metadata:
      labels:
        app: network-tools
        environment: stag
    spec:
      containers:
        - name: network-tools
          image: docker.io/dockerboi99/he_k8s:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 256Mi
