apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: he-api-dev

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - smoke-test.yaml

images:
  - name: docker.io/dockerboi99/he_k8s
    newName: docker.io/dockerboi99/he_k8s
    newTag: sha-3b498d90463e
