apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-tools-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://source.cyberspace.vn/nhatcm1/he_k8s.git
    targetRevision: main
    path: deploy/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: network-tools-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
